import Head from "next/head";
import type { NextPage } from "next";
import ServerState from "../components/ServerState";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading, isError } = trpc.useQuery(["order.get_next_two"], {
    refetchOnWindowFocus: false,
  });

  const [onDutyToday, onDutyTomorrow] = data || [];
  console.log("On Duty Today: ", onDutyToday);

  const getServerState = () => {
    if (isLoading) {
      return "Loading...";
    } else if (isError) {
      return "Error";
    }
  };

  const dateToday = new Date().toLocaleDateString("en-us", {
    weekday: "long",
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  return (
    <>
      <Head>
        <title>314 Water Duty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center h-[80%] p-4">
        {isLoading || isError ? (
          <ServerState isError={isError} isLoading={isLoading} />
        ) : (
          <>
            <div className="w-100 flex flex-col justify-center items-center ">
              <p className="text-xl p-0">Water Duty</p>
              <p className="text-4xl text-black py-6">
                <span className=" font-bold  text-purple-600 capitalize">
                  {onDutyToday?.name}
                </span>
              </p>
              <p className="text-xl p-0">{dateToday}</p>
            </div>
            <div className="py-6"></div>
            <p className="text-lg capitalize">
              Up Next: {onDutyTomorrow?.name}
            </p>
          </>
        )}
      </main>
    </>
  );
};

export default Home;
